import { isEqual } from './javascript'
import userIcon from '../assets/icons/user.svg'
export const LOGOUT = 'LOGOUT'

const userWiseRole = {
  admin: 1,
  stateHostelDepartment: 2, //consumer
  stateAdminOfficer: 3, //consumerUser
  districtCollector: 4, //Dealer
  districtCollectorAdmin: 5, //dealerUser
  districtHostelDepartment: 6, //recycler
  districtAdminOfficer: 37, //superUser
  inspectionOfficer: 38, //dataEntry
  hostel: 9,
}

const {
  admin,
  stateHostelDepartment,
  stateAdminOfficer,
  districtCollector,
  districtCollectorAdmin,
  districtHostelDepartment,
  districtAdminOfficer,
  inspectionOfficer,
  hostel,
} = userWiseRole

const childUsers = [
  stateAdminOfficer,
  districtCollectorAdmin,
  districtAdminOfficer,
  inspectionOfficer,
  hostel,
]

const userDataList = ({ roleId }) => {
  switch (roleId) {
    case admin:
      return {
        list: [
          {
            id: 1,
            roleId: admin,
            profileUrl: userIcon,
            lastName: 'Genba_Admin',
            businessName: 'Genba_Admin',
            emailId: 'genba.admin@gmail.com',
            phoneNumber: '123456789',
            address: '123-45th St.678',
            city: 'Noida',
            state: 'Uttar Pradesh',
            country: 'in',
            pincode: 201305,
            creationDate: 1753998390593,
            modificationDate: 0,
            adminId: 1,
            inchargeDepartment: null,
            inchargePerson: null,
          },
        ],
      }
    case stateHostelDepartment:
      return {
        list: [
          {
            id: 1,
            roleId: stateHostelDepartment,
            profileUrl: null,
            businessName: 'Scheduled Caste Development Department',
            lastName: 'Shardul Surma',
            emailId: 'Scwelfaretelangana@gmail',
            phoneNumber: '9898786756',
            address:
              'Scheduled Caste Development Department, Government of Telangana 3rd Floor, DSS Bhavan, Masab Tank',
            city: 'Hyderabad',
            state: 'Telangana',
            country: 'in',
            pincode: 500028,
            creationDate: 1753998390593,
            modificationDate: 0,
            adminId: 94,
            inchargeDepartment: null,
            inchargePerson: null,
          },
          {
            id: 2,
            roleId: stateHostelDepartment,
            profileUrl: null,
            businessName: 'Tribal Welfare Department',
            lastName: 'John Prabudoss',
            emailId: 'Stwelfaretelangana@gmail.com',
            phoneNumber: '8765784756',
            address:
              'Commissioner of Tribal Welfare Department, 6th Floor, D S S Bhavan, Masab Tank',
            city: 'Hyderabad',
            state: 'Telangana',
            country: 'in',
            pincode: 500028,
            creationDate: 1753998390593,
            modificationDate: 0,
            adminId: 95,
            inchargeDepartment: 'Sales',
            inchargePerson: 'John Doe',
          },
          {
            id: 3,
            roleId: stateHostelDepartment,
            profileUrl: null,
            businessName: 'Backward Classes Welfare Department',
            lastName: 'Rachell Johnson',
            emailId: 'bcwelfaretelangana@gmail.com',
            phoneNumber: '888',
            address:
              'Commissioner of Backward classes welfare Department, 6th Floor, D S S Bhavan, Masab Tank',
            city: 'Hyderabad',
            state: 'Telangana',
            country: 'in',
            pincode: 500028,
            creationDate: 1753998390593,
            modificationDate: 0,
            adminId: 96,
            inchargeDepartment: 'Marketing',
            inchargePerson: 'Jane Smith',
          },
        ],
      }
    case stateAdminOfficer:
      return {
        list: [
          {
            id: 1,
            roleId: stateAdminOfficer,
            profileUrl: null,
            lastName: 'Arvind Rao',
            emailId: 'arvind@gmail.com',
            phoneNumber: '7867678989',
            address: 'Secunderabad',
            city: '',
            state: '',
            country: '',
            pincode: null,
            creationDate: 1683708390593,
            modificationDate: 0,
          },
          {
            id: 2,
            roleId: stateAdminOfficer,
            profileUrl: null,
            lastName: 'Rajamohan',
            emailId: 'rajamohan@gmail.com',
            phoneNumber: '9845456745',
            address: 'Hyderabad',
            city: '',
            state: '',
            country: '',
            pincode: null,
            creationDate: 1683718390593,
            modificationDate: 0,
          },
          {
            id: 3,
            roleId: stateAdminOfficer,
            profileUrl: null,
            lastName: 'Balakrishna',
            emailId: 'balakrishna@gmail.com',
            phoneNumber: '8978676789',
            address: 'Malakpet',
            city: '',
            state: '',
            country: '',
            pincode: null,
            creationDate: 1683728390593,
            modificationDate: 0,
          },
        ],
      }
    case districtCollector:
      return {
        list: [
          {
            id: 1,
            roleId: districtCollector,
            profileUrl: null,
            businessName: 'Adilabad',
            lastName: 'Rahul Singh',
            emailId: 'adilabad@gmail.com',
            phoneNumber: '08732-227402',
            address: 'Adilabad District Collectorate',
            city: '',
            state: '',
            country: '',
            pincode: null,
            creationDate: 1683708390593,
            modificationDate: 0,
          },
          {
            id: 2,
            roleId: districtCollector,
            profileUrl: null,
            businessName: 'Nizamabad',
            firstName: 'Aman',
            lastName: 'Aman Kumar',
            emailId: 'Nizamabad bad@gmail.com',
            phoneNumber: '08732-227409',
            address: 'Nizamabad district Collectorate',
            city: '',
            state: '',
            country: '',
            pincode: null,
            creationDate: 1683718390593,
            modificationDate: 0,
          },
          {
            id: 3,
            roleId: districtCollector,
            profileUrl: null,
            businessName: 'Kamareddy',
            firstName: 'Jessica',
            lastName: 'Jessica Long',
            emailId: 'kamareddy@gmail.com',
            phoneNumber: '08755-227402',
            address: 'kamareddy district collectorate',
            city: '',
            state: '',
            country: '',
            pincode: null,
            creationDate: 1683728390593,
            modificationDate: 0,
          },
        ],
      }
    case districtCollectorAdmin:
      return {
        list: [
          {
            id: 1,
            roleId: districtCollectorAdmin,
            profileUrl: null,
            lastName: 'Aravind',
            emailId: 'aravindkumar@gmail.com',
            phoneNumber: '7834683479',
            address:
              'H. No. 4-72, Shivaji Nagar, Bhainsa, Adilabad District, Telangana – 504103',
            city: '',
            state: '',
            country: '',
            pincode: null,
            creationDate: 1683708390593,
            modificationDate: 0,
          },
          {
            id: 2,
            roleId: districtCollectorAdmin,
            profileUrl: null,
            lastName: 'Kruparkar',
            emailId: 'kruparkarrao@gmail.com',
            phoneNumber: '7889788909',
            address:
              'H. No. 3-98, Old Bus Stand Road, Bhainsa, Telangana – 504103',
            city: '',
            state: '',
            country: '',
            pincode: null,
            creationDate: 1683718390593,
            modificationDate: 0,
            adminId: 102,
            inchargeDepartment: 'Sales',
            inchargePerson: 'Rachell Johnson',
            parent: {},
          },
          {
            id: 3,
            roleId: districtCollectorAdmin,
            profileUrl: null,
            lastName: 'Shravan kumar ',
            level: 'Leader',
            emailId: 'shravankumar@gmail.com',
            phoneNumber: '8978676709',
            address:
              'Plot No. 27, Near Masjid-e-Noor, Nirmal Road, Bhainsa, Adilabad – 504103',
            city: '',
            state: '',
            country: '',
            pincode: null,
            creationDate: 1683728390593,
            modificationDate: 0,
            adminId: 103,
            inchargeDepartment: 'Operations',
            inchargePerson: 'Steven Clarke',
            parent: {},
          },
        ],
      }
    case districtHostelDepartment:
      return {
        list: [
          {
            id: 1,
            roleId: districtHostelDepartment,
            profileUrl: null,
            businessName: 'Nizamadad district hostel department ',
            lastName: 'Nizamadad',
            inchargeName: 'Jignesh Patel',
            emailId: 'nzbhosteldept@gmail.com',
            phoneNumber: '7867565678',
            address: 'Nizamabad collectorate office',
            city: '',
            state: '',
            country: '',
            pincode: null,
            creationDate: 1683708390593,
            modificationDate: 0,
          },
          {
            id: 2,
            roleId: districtHostelDepartment,
            profileUrl: null,
            businessName: 'Adilabad district hostel department ',
            lastName: 'SK Shah',
            inchargeName: 'SK Shah',
            emailId: 'adbhosteldept@gmail.com',
            phoneNumber: '7867678908',
            address: 'Adilabad collectorate office',
            city: '',
            state: '',
            country: '',
            pincode: null,
            creationDate: 1683718390593,
            modificationDate: 0,
          },
          {
            id: 3,
            roleId: districtHostelDepartment,
            profileUrl: null,
            businessName: 'Kamareddy district hostel department',
            lastName: 'Jake Usan',
            inchargeName: 'Jake Usan',
            emailId: 'kmrhosteldept@gmail.com',
            phoneNumber: '7899097808',
            address: 'Kamareddy collectorate office',
            city: '',
            state: '',
            country: '',
            pincode: null,
            creationDate: 1683728390593,
            modificationDate: 0,
          },
        ],
      }
    case districtAdminOfficer:
      return {
        list: [
          {
            id: 1,
            roleId: districtAdminOfficer,
            profileUrl: null,
            lastName: 'Kumar harsha',
            inchargeName: 'Jignesh Patel',
            emailId: 'kumar.harsha@gmail.com',
            phoneNumber: '8798879080',
            address:
              'Shop No. 12, Gandhi Chowk Market, Bhainsa Town, Adilabad – 504103',
            city: '',
            state: '',
            country: '',
            pincode: null,
            creationDate: 1683708390593,
            modificationDate: 0,
          },
          {
            id: 2,
            roleId: districtAdminOfficer,
            profileUrl: null,
            lastName: 'Harish reddy',
            inchargeName: 'Jignesh Patel',
            emailId: 'Harishreddy@gmail.com',
            phoneNumber: '8734943738',
            address:
              'H. No. 2-15, Ambedkar Chowk, Main Road, Bhainsa, Telangana – 504103',
            city: '',
            state: '',
            country: '',
            pincode: null,
            creationDate: 1683708390593,
            modificationDate: 0,
          },
          {
            id: 3,
            roleId: districtAdminOfficer,
            profileUrl: null,
            lastName: 'Anirudh  ',
            inchargeName: 'Jignesh Patel',
            emailId: 'Anirudh.007@gmail.com',
            phoneNumber: '7846577468',
            address:
              'H. No. 5-72, Shivaji Nagar, Bhainsa, Adilabad District, Telangana – 504103',
            city: '',
            state: '',
            country: '',
            pincode: null,
            creationDate: 1683708390593,
            modificationDate: 0,
          },
        ],
      }
    case inspectionOfficer:
      return {
        list: [
          {
            id: 1,
            roleId: inspectionOfficer,
            profileUrl: userIcon,
            lastName: 'Suresh',
            emailId: 'sureshyadav@gmail.com',
            phoneNumber: '9989897768',
            address:
              'H. No. 1-44, Basar Road, Near Hanuman Temple, Bhainsa, Telangana – 504103',
            city: '',
            state: '',
            country: '',
            pincode: null,
            creationDate: 1683708390593,
            modificationDate: 0,
          },
          {
            id: 2,
            roleId: inspectionOfficer,
            profileUrl: userIcon,
            lastName: 'Naresh',
            emailId: 'naresh.kumar@gmail.com',
            phoneNumber: '8888888888',
            address:
              'H. No. 5-61, Azad Gunj, Bhainsa Town, Adilabad District – 504103',
            city: '',
            state: '',
            country: '',
            pincode: null,
            creationDate: 1683718390593,
            modificationDate: 0,
          },
          {
            id: 3,
            roleId: inspectionOfficer,
            profileUrl: userIcon,
            lastName: 'Prem',
            emailId: 'premkumar@gmial.com',
            phoneNumber: '7837837837',
            address:
              'Shop No. 8, RTC Complex, Bus Stand Area, Bhainsa – 504103',
            city: '',
            state: '',
            country: '',
            pincode: null,
            creationDate: 1683728390593,
            modificationDate: 0,
          },
        ],
      }
    case hostel:
      return {
        list: [
          {
            id: 1,
            roleId: hostel,
            profileUrl: userIcon,
            lastName: 'Ekalavya Model Residential School',
            emailId: 'ankit.sharma@gmail.com',
            phoneNumber: '9988776655',
            address:
              'H. No. 2-77, Near Jama Masjid, Old City Area, Bhainsa – 504103',
            city: '',
            state: '',
            country: '',
            pincode: null,
            creationDate: 1683708390593,
            modificationDate: 0,
            adminId: 201,
            parent: {},
          },
          {
            id: 2,
            roleId: hostel,
            profileUrl: userIcon,
            lastName: 'Govt. BC Hostel',
            emailId: 'priya.das@example.com',
            phoneNumber: '9876541230',
            address:
              'H. No. 7-19, Teachers Colony, Nizamabad, Telangana – 504103',
            city: '',
            state: '',
            country: '',
            pincode: null,
            creationDate: 1683718390593,
            modificationDate: 0,
            adminId: 202,
            parent: {},
          },
          {
            id: 3,
            roleId: hostel,
            profileUrl: userIcon,
            lastName: 'Govt. BC College',
            emailId: 'arjun.verma@example.com',
            phoneNumber: '9123456780',
            address:
              'H. No. 5-61, Azad Gunj, Armoor Town, Nizamabad District – 504103',
            city: '',
            state: '',
            country: '',
            pincode: null,
            creationDate: 1683728390593,
            modificationDate: 0,
            adminId: 203,
            parent: {},
          },
          {
            id: 4,
            roleId: hostel,
            profileUrl: userIcon,
            lastName: 'Govt. ST Ashram School',
            emailId: 'nisha.kaur@samplemail.com',
            phoneNumber: '9012345678',
            address:
              'H. No. 7-19, Teachers Colony, Balkonda, Telangana – 504103',
            city: '',
            state: '',
            country: '',
            pincode: null,
            creationDate: 1683738390593,
            modificationDate: 0,
            adminId: 204,
            parent: {},
          },
          {
            id: 5,
            roleId: hostel,
            profileUrl: userIcon,
            lastName: 'Govt. ST Hostel',
            emailId: 'rohit.kulkarni@gmail.com',
            phoneNumber: '8901234567',
            address:
              'H. No. 3-42, Near Gandhi Chowk, Yellareddy, Nizamabad District, Telangana – 504103',
            city: '',
            state: '',
            country: '',
            pincode: null,
            creationDate: 1683748390593,
            modificationDate: 0,
            adminId: 205,
            parent: {},
          },
          {
            id: 6,
            roleId: hostel,
            profileUrl: userIcon,
            lastName: 'Govt. ST PMH',
            emailId: 'rohit.kulkarni@gmail.com',
            phoneNumber: '8901234567',
            address: 'H. No. 5-67, Vivekananda Colony, Adilabad – 504103',
            city: '',
            state: '',
            country: '',
            pincode: null,
            creationDate: 1683748390593,
            modificationDate: 0,
            adminId: 205,
            parent: {},
          },
          {
            id: 7,
            roleId: hostel,
            profileUrl: userIcon,
            lastName: 'Govt. ST Hostel',
            emailId: 'rohit.kulkarni@gmail.com',
            phoneNumber: '8901234567',
            address: 'H. No. 3-77, Bodhan, Telangana – 504103',
            city: '',
            state: '',
            country: '',
            pincode: null,
            creationDate: 1683748390593,
            modificationDate: 0,
            adminId: 205,
            parent: {},
          },
        ],
      }
    default:
      return { list: [] }
  }
}

const getDummyUser = ({ roleId, userId }) => {
  const userList = userDataList({ roleId })?.list
  return userList?.find(user => isEqual(user?.id, userId)) || userList?.[0]
}

export { childUsers, userDataList, userWiseRole, getDummyUser }
