import { isEqual } from './javascript'
import userIcon from '../assets/icons/user.svg'
export const LOGOUT = 'LOGOUT'

const userWiseRole = {
  admin: 1,
  stateHostelDepartment: 2, //consumer
  stateAdminOfficer: 3, //consumerUser
  districtCollector: 4, //Dealer
  districtCollectorAdmin: 5, //dealerUser
  districtHostelDepartment: 6, //recycler
  districtAdminOfficer: 37, //superUser
  inspectionOfficer: 38, //dataEntry
  hostel: 9,
}

const {
  admin,
  stateHostelDepartment,
  stateAdminOfficer,
  // districtCollector,
  districtCollectorAdmin,
  // districtHostelDepartment,
  districtAdminOfficer,
  inspectionOfficer,
  hostel,
} = userWiseRole

const childUsers = [
  stateAdminOfficer,
  districtCollectorAdmin,
  districtAdminOfficer,
  inspectionOfficer,
  hostel,
]

const userDataList = ({ roleId }) => {
  switch (roleId) {
    case admin:
      return {
        list: [
          {
            id: 1,
            roleId: admin,
            profileUrl: userIcon,
            lastName: 'Genba_Admin',
            businessName: 'Genba_Admin',
            emailId: 'genba.admin@gmail.com',
            phoneNumber: '123456789',
            address: '123-45th St.678',
            city: 'Noida',
            state: 'Uttar Pradesh',
            country: 'in',
            pincode: 201305,
            creationDate: 1753998390593,
            modificationDate: 0,
            adminId: 1,
            inchargeDepartment: null,
            inchargePerson: null,
          },
        ],
      }
    case stateHostelDepartment:
      return {
        list: [
          {
            id: 1,
            roleId: stateHostelDepartment,
            profileUrl: null,
            businessName: 'Scheduled Caste Development Department',
            lastName: 'Shardul Surma',
            emailId: 'Scwelfaretelangana@gmail',
            phoneNumber: '9898786756',
            address:
              'Scheduled Caste Development Department, Government of Telangana 3rd Floor, DSS Bhavan, Masab Tank',
            city: 'Hyderabad',
            state: 'Telangana',
            country: 'in',
            pincode: 500028,
            creationDate: 1753998390593,
            modificationDate: 0,
            adminId: 94,
            inchargeDepartment: null,
            inchargePerson: null,
          },
          {
            id: 2,
            roleId: stateHostelDepartment,
            profileUrl: null,
            businessName: 'Tribal Welfare Department',
            lastName: 'John Prabudoss',
            emailId: 'Stwelfaretelangana@gmail.com',
            phoneNumber: '8765784756',
            address:
              'Commissioner of Tribal Welfare Department, 6th Floor, D S S Bhavan, Masab Tank',
            city: 'Hyderabad',
            state: 'Telangana',
            country: 'in',
            pincode: 500028,
            creationDate: 1753998390593,
            modificationDate: 0,
            adminId: 95,
            inchargeDepartment: 'Sales',
            inchargePerson: 'John Doe',
          },
          {
            id: 3,
            roleId: stateHostelDepartment,
            profileUrl: null,
            businessName: 'Backward Classes Welfare Department',
            lastName: 'Rachell Johnson',
            emailId: 'bcwelfaretelangana@gmail.com',
            phoneNumber: '888',
            address:
              'Commissioner of Backward classes welfare Department, 6th Floor, D S S Bhavan, Masab Tank',
            city: 'Hyderabad',
            state: 'Telangana',
            country: 'in',
            pincode: 500028,
            creationDate: 1753998390593,
            modificationDate: 0,
            adminId: 96,
            inchargeDepartment: 'Marketing',
            inchargePerson: 'Jane Smith',
          },
        ],
      }
    // case stateAdminOfficer:
    //   return {
    //     list: [
    //       {
    //         id: 1,
    //         roleId: store,
    //         profileUrl: mart1,
    //         businessName: 'John Mart 1',
    //         inchargeName: 'Suneetha Sagar',
    //         lastName: 'John Mart 1',
    //         emailId: 'suneetha@gmail.com',
    //         phoneNumber: '1234567890',
    //         address: '101 Main Avenue, Connaught Place',
    //         city: 'Delhi',
    //         state: 'Delhi',
    //         country: 'in',
    //         pincode: 110001,
    //         creationDate: 1683708390593,
    //         modificationDate: 0,
    //         adminId: 401,
    //         parent: {},
    //       },
    //       {
    //         id: 2,
    //         roleId: store,
    //         profileUrl: mart1,
    //         businessName: 'John Mart 2',
    //         inchargeName: 'Suneetha Sagar',
    //         lastName: 'John Mart 2',
    //         emailId: 'suneetha@gmail.com',
    //         phoneNumber: '9876541230',
    //         address: '500 MG Road, Block A',
    //         city: 'Bangalore',
    //         state: 'Karnataka',
    //         country: 'in',
    //         pincode: 560001,
    //         creationDate: 1683718390593,
    //         modificationDate: 0,
    //         adminId: 402,
    //         parent: {},
    //       },
    //       {
    //         id: 3,
    //         roleId: store,
    //         profileUrl: mart1,
    //         businessName: 'John Mart 3',
    //         inchargeName: 'Suneetha Sagar',
    //         lastName: 'John Mart 3',
    //         emailId: 'suneetha@gmail.com',
    //         phoneNumber: '9123456780',
    //         address: '12 Marine Drive, Block C',
    //         city: 'Mumbai',
    //         state: 'Maharashtra',
    //         country: 'in',
    //         pincode: 400020,
    //         creationDate: 1683728390593,
    //         modificationDate: 0,
    //         adminId: 403,
    //         parent: {},
    //       },
    //       {
    //         id: 4,
    //         roleId: store,
    //         profileUrl: mart1,
    //         businessName: 'John Mart 4',
    //         inchargeName: 'Suneetha Sagar',
    //         lastName: 'John Mart 4',
    //         emailId: 'suneetha@gmail.com',
    //         phoneNumber: '9012345678',
    //         address: '100 Salt Lake, Sector 5',
    //         city: 'Kolkata',
    //         state: 'West Bengal',
    //         country: 'in',
    //         pincode: 700091,
    //         creationDate: 1683738390593,
    //         modificationDate: 0,
    //         adminId: 404,
    //         parent: {},
    //       },
    //     ],
    //   }
    // case districtCollector:
    //   return {
    //     list: [
    //       {
    //         id: 1,
    //         roleId: storeManager,
    //         profileUrl: user3,
    //         businessName: 'John Mart 1',
    //         firstName: 'Rahul',
    //         lastName: 'Rahul Singh',
    //         level: 'Manager',
    //         emailId: 'lorem@gmail.com',
    //         phoneNumber: '9876543210',
    //         address: '123-45th St.678',
    //         city: 'Noida',
    //         state: 'Uttar Pradesh',
    //         country: 'in',
    //         pincode: 201305,
    //         creationDate: 1683708390593,
    //         modificationDate: 0,
    //         adminId: 101,
    //         inchargeDepartment: 'Management',
    //         inchargePerson: 'John Prabudoss',
    //         parent: {},
    //       },
    //       {
    //         id: 2,
    //         roleId: storeManager,
    //         profileUrl: user4,
    //         businessName: 'John Mart 1',
    //         firstName: 'Aman',
    //         lastName: 'Aman Kumar',
    //         level: 'Manager',
    //         emailId: 'lorem@gmail.com',
    //         phoneNumber: '9123456789',
    //         address: '456-78th St.789',
    //         city: 'Bangalore',
    //         state: 'Karnataka',
    //         country: 'in',
    //         pincode: 560001,
    //         creationDate: 1683718390593,
    //         modificationDate: 0,
    //         adminId: 102,
    //         inchargeDepartment: 'Sales',
    //         inchargePerson: 'Rachell Johnson',
    //         parent: {},
    //       },
    //       {
    //         id: 3,
    //         roleId: storeManager,
    //         profileUrl: user5,
    //         businessName: 'John Mart 2',
    //         firstName: 'Jessica',
    //         lastName: 'Jessica Long',
    //         level: 'Manager',
    //         emailId: 'lorem@gmail.com',
    //         phoneNumber: '9034567890',
    //         address: '789-01th St.101',
    //         city: 'Mumbai',
    //         state: 'Maharashtra',
    //         country: 'in',
    //         pincode: 400059,
    //         creationDate: 1683728390593,
    //         modificationDate: 0,
    //         adminId: 103,
    //         inchargeDepartment: 'Operations',
    //         inchargePerson: 'Steven Clarke',
    //         parent: {},
    //       },
    //       {
    //         id: 4,
    //         roleId: storeManager,
    //         profileUrl: user6,
    //         businessName: 'John Mart 2',
    //         firstName: 'Sam',
    //         lastName: 'Sam Smith',
    //         level: 'Manager',
    //         emailId: 'lorem@gmail.com',
    //         phoneNumber: '9988776655',
    //         address: '102-23th St.567',
    //         city: 'Chennai',
    //         state: 'Tamil Nadu',
    //         country: 'in',
    //         pincode: 600001,
    //         creationDate: 1683738390593,
    //         modificationDate: 0,
    //         adminId: 104,
    //         inchargeDepartment: 'Customer Service',
    //         inchargePerson: 'Anna White',
    //         parent: {},
    //       },
    //     ],
    //   }
    // case districtCollectorAdmin:
    //   return {
    //     list: [
    //       {
    //         id: 1,
    //         roleId: storeEmployee,
    //         profileUrl: user3,
    //         businessName: 'John Mart 1',
    //         firstName: 'Rahul',
    //         lastName: 'Rahul Singh',
    //         level: 'Leader',
    //         emailId: 'lorem@gmail.com',
    //         phoneNumber: '9876543210',
    //         address: '123-45th St.678',
    //         city: 'Noida',
    //         state: 'Uttar Pradesh',
    //         country: 'in',
    //         pincode: 201305,
    //         creationDate: 1683708390593,
    //         modificationDate: 0,
    //         adminId: 101,
    //         inchargeDepartment: 'Management',
    //         inchargePerson: 'John Prabudoss',
    //         parent: {},
    //       },
    //       {
    //         id: 2,
    //         roleId: storeEmployee,
    //         profileUrl: user4,
    //         businessName: 'John Mart 1',
    //         firstName: 'Aman',
    //         lastName: 'Aman Kumar',
    //         level: 'Regular',
    //         emailId: 'lorem@gmail.com',
    //         phoneNumber: '9123456789',
    //         address: '456-78th St.789',
    //         city: 'Bangalore',
    //         state: 'Karnataka',
    //         country: 'in',
    //         pincode: 560001,
    //         creationDate: 1683718390593,
    //         modificationDate: 0,
    //         adminId: 102,
    //         inchargeDepartment: 'Sales',
    //         inchargePerson: 'Rachell Johnson',
    //         parent: {},
    //       },
    //       {
    //         id: 3,
    //         roleId: storeEmployee,
    //         profileUrl: user5,
    //         businessName: 'John Mart 2',
    //         firstName: 'Jessica',
    //         lastName: 'Jessica Long',
    //         level: 'Leader',
    //         emailId: 'lorem@gmail.com',
    //         phoneNumber: '9034567890',
    //         address: '789-01th St.101',
    //         city: 'Mumbai',
    //         state: 'Maharashtra',
    //         country: 'in',
    //         pincode: 400059,
    //         creationDate: 1683728390593,
    //         modificationDate: 0,
    //         adminId: 103,
    //         inchargeDepartment: 'Operations',
    //         inchargePerson: 'Steven Clarke',
    //         parent: {},
    //       },
    //       {
    //         id: 4,
    //         roleId: storeEmployee,
    //         profileUrl: user6,
    //         businessName: 'John Mart 2',
    //         firstName: 'Sam',
    //         lastName: 'Sam Smith',
    //         level: 'Regular',
    //         emailId: 'lorem@gmail.com',
    //         phoneNumber: '9988776655',
    //         address: '102-23th St.567',
    //         city: 'Chennai',
    //         state: 'Tamil Nadu',
    //         country: 'in',
    //         pincode: 600001,
    //         creationDate: 1683738390593,
    //         modificationDate: 0,
    //         adminId: 104,
    //         inchargeDepartment: 'Customer Service',
    //         inchargePerson: 'Anna White',
    //         parent: {},
    //       },
    //       {
    //         id: 5,
    //         roleId: storeEmployee,
    //         profileUrl: user7,
    //         businessName: 'John Mart 3',
    //         firstName: '',
    //         lastName: 'George',
    //         level: 'Leader',
    //         emailId: 'lorem@gmail.com',
    //         phoneNumber: '9988776655',
    //         address: '102-23th St.567',
    //         city: 'Chennai',
    //         state: 'Tamil Nadu',
    //         country: 'in',
    //         pincode: 600001,
    //         creationDate: 1683738390593,
    //         modificationDate: 0,
    //         adminId: 104,
    //         inchargeDepartment: 'Customer Service',
    //         inchargePerson: 'Anna White',
    //         parent: {},
    //       },
    //       {
    //         id: 6,
    //         roleId: storeEmployee,
    //         profileUrl: user8,
    //         businessName: 'John Mart 3',
    //         firstName: '',
    //         lastName: 'Steven',
    //         level: 'Leader',
    //         emailId: 'lorem@gmail.com',
    //         phoneNumber: '9988776655',
    //         address: '102-23th St.567',
    //         city: 'Chennai',
    //         state: 'Tamil Nadu',
    //         country: 'in',
    //         pincode: 600001,
    //         creationDate: 1683738390593,
    //         modificationDate: 0,
    //         adminId: 104,
    //         inchargeDepartment: 'Customer Service',
    //         inchargePerson: 'Anna White',
    //         parent: {},
    //       },
    //     ],
    //   }
    // case districtHostelDepartment:
    //   return {
    //     list: [
    //       {
    //         id: 1,
    //         roleId: vendor,
    //         profileUrl: vendor1,
    //         businessName: 'Sunrise',
    //         lastName: '',
    //         inchargeName: 'Jignesh Patel',
    //         emailId: 'jignesh.patel@sunrise.com',
    //         phoneNumber: '9876543210',
    //         address: '456-78th Avenue, Block B',
    //         city: 'Noida',
    //         state: 'Uttar Pradesh',
    //         country: 'in',
    //         pincode: 201309,
    //         creationDate: 1683708390593,
    //         modificationDate: 0,
    //         adminId: 101,
    //         parent: {},
    //       },
    //       {
    //         id: 2,
    //         roleId: vendor,
    //         profileUrl: vendor2,
    //         businessName: 'SK Suppliers',
    //         lastName: '',
    //         inchargeName: 'SK Shah',
    //         emailId: 'sk.shah@sk-suppliers.com',
    //         phoneNumber: '9123456789',
    //         address: '789 Main Street, Building 4, Tech Park',
    //         city: 'Bangalore',
    //         state: 'Karnataka',
    //         country: 'in',
    //         pincode: 560002,
    //         creationDate: 1683718390593,
    //         modificationDate: 0,
    //         adminId: 102,
    //         parent: {},
    //       },
    //       {
    //         id: 3,
    //         roleId: vendor,
    //         profileUrl: vendor3,
    //         businessName: 'Lorem Ipsum',
    //         lastName: '',
    //         inchargeName: 'Jake Usan',
    //         emailId: 'jake.usan@loremipsum.com',
    //         phoneNumber: '8234567890',
    //         address: '321 First Avenue, Block C, Industrial Area',
    //         city: 'Mumbai',
    //         state: 'Maharashtra',
    //         country: 'in',
    //         pincode: 400060,
    //         creationDate: 1683728390593,
    //         modificationDate: 0,
    //         adminId: 103,
    //         parent: {},
    //       },
    //       {
    //         id: 4,
    //         roleId: vendor,
    //         profileUrl: vendor4,
    //         businessName: 'Techno Goods',
    //         lastName: '',
    //         inchargeName: 'Smith Lee',
    //         emailId: 'smith.lee@technogoods.com',
    //         phoneNumber: '9345678901',
    //         address: '102 Tech Lane, Industrial District, Block D',
    //         city: 'Chennai',
    //         state: 'Tamil Nadu',
    //         country: 'in',
    //         pincode: 600002,
    //         creationDate: 1683738390593,
    //         modificationDate: 0,
    //         adminId: 104,
    //         parent: {},
    //       },
    //     ],
    //   }
    // case districtAdminOfficer:
    //   return {
    //     list: [
    //       {
    //         id: 1,
    //         roleId: manufacturer,
    //         profileUrl: vendor1,
    //         businessName: 'Virginia Lottery',
    //         firmName: '',
    //         lastName: '',
    //         inchargeName: 'Jignesh Patel',
    //         emailId: 'lorem.ipsum@gmail.com',
    //         phoneNumber: '9988776655',
    //         address: '102 Finance Tower, Level 3',
    //         city: 'Mumbai',
    //         state: 'Maharashtra',
    //         country: 'in',
    //         pincode: 400021,
    //         creationDate: 1683708390593,
    //         modificationDate: 0,
    //         adminId: 501,
    //         parent: {},
    //       },
    //     ],
    //   }
    // case inspectionOfficer:
    //   return {
    //     list: [
    //       {
    //         id: 1,
    //         roleId: customer,
    //         profileUrl: userIcon,
    //         lastName: 'Ankit Sharma',
    //         emailId: 'ankit.sharma@gmail.com',
    //         phoneNumber: '9988776655',
    //         address: '123 Green Lane, Apartment 5A',
    //         city: 'Pune',
    //         state: 'Maharashtra',
    //         country: 'in',
    //         pincode: 411001,
    //         creationDate: 1683708390593,
    //         modificationDate: 0,
    //         adminId: 201,
    //         parent: {},
    //       },
    //       {
    //         id: 2,
    //         roleId: customer,
    //         profileUrl: userIcon,
    //         lastName: 'Priya Das',
    //         emailId: 'priya.das@example.com',
    //         phoneNumber: '9876541230',
    //         address: '456 Sunset Boulevard, Villa 10',
    //         city: 'Kolkata',
    //         state: 'West Bengal',
    //         country: 'in',
    //         pincode: 700019,
    //         creationDate: 1683718390593,
    //         modificationDate: 0,
    //         adminId: 202,
    //         parent: {},
    //       },
    //       {
    //         id: 3,
    //         roleId: customer,
    //         profileUrl: userIcon,
    //         lastName: 'Arjun Verma',
    //         emailId: 'arjun.verma@example.com',
    //         phoneNumber: '9123456780',
    //         address: '32 Elm Street, Block B',
    //         city: 'Hyderabad',
    //         state: 'Telangana',
    //         country: 'in',
    //         pincode: 500081,
    //         creationDate: 1683728390593,
    //         modificationDate: 0,
    //         adminId: 203,
    //         parent: {},
    //       },
    //       {
    //         id: 4,
    //         roleId: customer,
    //         profileUrl: userIcon,
    //         lastName: 'Nisha Kaur',
    //         emailId: 'nisha.kaur@samplemail.com',
    //         phoneNumber: '9012345678',
    //         address: '78 Maple Avenue, Floor 3',
    //         city: 'Chandigarh',
    //         state: 'Punjab',
    //         country: 'in',
    //         pincode: 160017,
    //         creationDate: 1683738390593,
    //         modificationDate: 0,
    //         adminId: 204,
    //         parent: {},
    //       },
    //       {
    //         id: 5,
    //         roleId: customer,
    //         profileUrl: userIcon,
    //         lastName: 'Rohit Kulkarni',
    //         emailId: 'rohit.kulkarni@gmail.com',
    //         phoneNumber: '8901234567',
    //         address: '15 Pine Street, Villa B-1',
    //         city: 'Ahmedabad',
    //         state: 'Gujarat',
    //         country: 'in',
    //         pincode: 380015,
    //         creationDate: 1683748390593,
    //         modificationDate: 0,
    //         adminId: 205,
    //         parent: {},
    //       },
    //     ],
    //   }
    case hostel:
      return {
        list: [
          {
            id: 1,
            roleId: hostel,
            profileUrl: userIcon,
            lastName: 'Ekalavya Model Residential School',
            emailId: 'ankit.sharma@gmail.com',
            phoneNumber: '9988776655',
            address:
              'H. No. 2-77, Near Jama Masjid, Old City Area, Bhainsa – 504103',
            city: '',
            state: '',
            country: '',
            pincode: null,
            creationDate: 1683708390593,
            modificationDate: 0,
            adminId: 201,
            parent: {},
          },
          {
            id: 2,
            roleId: hostel,
            profileUrl: userIcon,
            lastName: 'Govt. BC Hostel',
            emailId: 'priya.das@example.com',
            phoneNumber: '9876541230',
            address:
              'H. No. 7-19, Teachers Colony, Nizamabad, Telangana – 504103',
            city: '',
            state: '',
            country: '',
            pincode: null,
            creationDate: 1683718390593,
            modificationDate: 0,
            adminId: 202,
            parent: {},
          },
          {
            id: 3,
            roleId: hostel,
            profileUrl: userIcon,
            lastName: 'Govt. BC College',
            emailId: 'arjun.verma@example.com',
            phoneNumber: '9123456780',
            address:
              'H. No. 5-61, Azad Gunj, Armoor Town, Nizamabad District – 504103',
            city: '',
            state: '',
            country: '',
            pincode: null,
            creationDate: 1683728390593,
            modificationDate: 0,
            adminId: 203,
            parent: {},
          },
          {
            id: 4,
            roleId: hostel,
            profileUrl: userIcon,
            lastName: 'Govt. ST Ashram School',
            emailId: 'nisha.kaur@samplemail.com',
            phoneNumber: '9012345678',
            address:
              'H. No. 7-19, Teachers Colony, Balkonda, Telangana – 504103',
            city: '',
            state: '',
            country: '',
            pincode: null,
            creationDate: 1683738390593,
            modificationDate: 0,
            adminId: 204,
            parent: {},
          },
          {
            id: 5,
            roleId: hostel,
            profileUrl: userIcon,
            lastName: 'Govt. ST Hostel',
            emailId: 'rohit.kulkarni@gmail.com',
            phoneNumber: '8901234567',
            address:
              'H. No. 3-42, Near Gandhi Chowk, Yellareddy, Nizamabad District, Telangana – 504103',
            city: '',
            state: '',
            country: '',
            pincode: null,
            creationDate: 1683748390593,
            modificationDate: 0,
            adminId: 205,
            parent: {},
          },
          {
            id: 6,
            roleId: hostel,
            profileUrl: userIcon,
            lastName: 'Govt. ST PMH',
            emailId: 'rohit.kulkarni@gmail.com',
            phoneNumber: '8901234567',
            address: 'H. No. 5-67, Vivekananda Colony, Adilabad – 504103',
            city: '',
            state: '',
            country: '',
            pincode: null,
            creationDate: 1683748390593,
            modificationDate: 0,
            adminId: 205,
            parent: {},
          },
          {
            id: 7,
            roleId: hostel,
            profileUrl: userIcon,
            lastName: 'Govt. ST Hostel',
            emailId: 'rohit.kulkarni@gmail.com',
            phoneNumber: '8901234567',
            address: 'H. No. 3-77, Bodhan, Telangana – 504103',
            city: '',
            state: '',
            country: '',
            pincode: null,
            creationDate: 1683748390593,
            modificationDate: 0,
            adminId: 205,
            parent: {},
          },
        ],
      }
    default:
      return { list: [] }
  }
}

const getDummyUser = ({ roleId, userId }) => {
  const userList = userDataList({ roleId })?.list
  return userList?.find(user => isEqual(user?.id, userId)) || userList?.[0]
}

export { childUsers, userDataList, userWiseRole, getDummyUser }
